// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhubgojrynqhfkjrrzaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhodWJnb2pyeW5xaGZranJyemFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzc4ODMsImV4cCI6MjA3MDgxMzg4M30.Mi29tV2SklT2gChppMV2qA5mMpZM_Bm8PwxBueBTA68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});